version: 2

models:
  - name: cc_stock
    columns:
      ### PK ###
      - name: product_id
        tests:
          - unique
      - name: product_name
        tests:
          - not_null
      - name: model_type
        tests:
          - not_null
